// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfesLNqD7eu0Ol_douj6jMyIxI_wmsyrM',
    appId: '1:194908899359:web:557d26939701b8492bad2a',
    messagingSenderId: '194908899359',
    projectId: 'app-two-cat-2c9fe',
    authDomain: 'app-two-cat-2c9fe.firebaseapp.com',
    storageBucket: 'app-two-cat-2c9fe.appspot.com',
    measurementId: 'G-NN3VGKBWYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe3dDSr4dMObSA_ssVUZax28sc-HeYR3c',
    appId: '1:194908899359:android:622c45e94cd1d0812bad2a',
    messagingSenderId: '194908899359',
    projectId: 'app-two-cat-2c9fe',
    storageBucket: 'app-two-cat-2c9fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Yc_iheVBAWZdsA9i9nFzNeQQ6HGZZ4k',
    appId: '1:194908899359:ios:352f011c4beae7812bad2a',
    messagingSenderId: '194908899359',
    projectId: 'app-two-cat-2c9fe',
    storageBucket: 'app-two-cat-2c9fe.appspot.com',
    iosBundleId: 'com.girinhong.appTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Yc_iheVBAWZdsA9i9nFzNeQQ6HGZZ4k',
    appId: '1:194908899359:ios:10a9656bf193a8762bad2a',
    messagingSenderId: '194908899359',
    projectId: 'app-two-cat-2c9fe',
    storageBucket: 'app-two-cat-2c9fe.appspot.com',
    iosBundleId: 'com.example.appTwo.RunnerTests',
  );
}
